CREATE TABLE CLAIM_FACT
(IDNO INT NOT NULL
,ClaimID	INT NOT NULL
,ClaimLineNum INT NOT NULL
,ClaimStatusCd CHAR(1) NOT NULL
,ClaimType CHAR(1) NOT NULL
,MemberID	INT NOT NULL
,ProviderID	INT NOT NULL
,posID	INT NOT NULL
,ServiceDate	DATE NOT NULL
,LoadDate	DATE NOT NULL
,Code_Type VARCHAR(10) NOT NULL
,Code_Value VARCHAR(10) NOT NULL
,Cases DECIMAL(12,0) NOT NULL
,Services DECIMAL(12,0) NOT NULL
,AllowedCharges DECIMAL(14,2) NOT NULL
,PaidClaims	DECIMAL(14,2) NOT NULL
,MemberPaid DECIMAL(14,2) NOT NULL
,OPL DECIMAL(14,2) NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_PROVIDER
(ProviderID INT NOT NULL
,SpecialtyID INT NOT NULL
,ProviderType INT NOT NULL
,OrgName VARCHAR(100) NOT NULL
,FirstName	VARCHAR(100)  NOT NULL
,LastName	VARCHAR(100) NOT NULL
,address_street	VARCHAR(255)
,address_city	VARCHAR(100)
,address_county	VARCHAR(50)
,address_state	CHAR(2)
,address_zip	CHAR(5)
,PRIMARY KEY (ProviderID)
);

CREATE TABLE DIM_MEMBER
(IDNO	INT NOT NULL
,memberID	INT NOT NULL
,Gender	CHAR(1) NOT NULL
,dateOfBirth	DATE  NOT NULL
,firstname	VARCHAR(100) NOT NULL
,lastname	VARCHAR(100) NOT NULL
,address_street	VARCHAR(255)
,address_city	VARCHAR(100)
,address_County	VARCHAR(50)
,address_state	CHAR(2)
,address_zip	CHAR(5) 
,Product	CHAR(3) NOT NULL
,Client_ID CHAR(6) NOT NULL
,StartDate	DATE  NOT NULL
,EndDate	DATE  NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_MEMBER_CONDITION
(IDNO INT NOT NULL
,memberID	INT NOT NULL
,DIABETES INT NOT NULL
,CAD INT NOT NULL
,CHF INT NOT NULL
,HYPERTENSION INT NOT NULL
,COPD INT NOT NULL
,StartDate	DATE  NOT NULL
,EndDate	DATE  NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_DATE
(IncMonth DATE NOT NULL
,IncMonthNum	INT NOT NULL
,StartDate	DATE  NOT NULL
,EndDate	DATE  NOT NULL
,tValue0 INT NOT NULL
,PRIMARY KEY (IncMonth)
);

CREATE TABLE DIM_PLACE_OF_SERVICE
(posID INT NOT NULL
,pos_Desc VARCHAR(100) NOT NULL
,pos_category VARCHAR(10) NOT NULL
,PRIMARY KEY (posID)
);

CREATE TABLE DIM_PROVIDER_SPECIALTY
(SpecialtyID INT NOT NULL
,Specialty_Desc	VARCHAR(100) NOT NULL
,SpecRup_Cd	  VARCHAR(10) NOT NULL
,SpecRup_DESC	VARCHAR(100) NOT NULL
,SpecType VARCHAR(10) NOT NULL
,PRIMARY KEY (SpecialtyID)
);

CREATE TABLE DIM_PROCEDURE
(IDNO INT NOT NULL
,Code_Type VARCHAR(10) NOT NULL
,Code_Value VARCHAR(10) NOT NULL
,PROCEDURE_DESC VARCHAR(255) NOT NULL
,FACILITY_CD VARCHAR(10) NOT NULL
,PROF_CD VARCHAR(10) NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_REPORTING_CATEGORY
(RPT_CD  VARCHAR(10) NOT NULL
,LVL_01	VARCHAR(10) NOT NULL
,LVL_02	VARCHAR(100) NOT NULL
,LVL_03	VARCHAR(100) NOT NULL
,PRIMARY KEY (RPT_CD)
);


CREATE TABLE SUM_MEMBER_CT
(IDNO	INT NOT NULL
,MemberID	INT NOT NULL
,PRODUCT	CHAR(3) NOT NULL
,CLIENT_ID	CHAR(6) NOT NULL
,Gender	CHAR(1) NOT NULL
,AgeRange	VARCHAR(20) NOT NULL
,MemberRegion	VARCHAR(20) NOT NULL
,DIABETES	INT NOT NULL
,CAD	INT NOT NULL
,CHF	INT NOT NULL
,HYPERTENSION	INT NOT NULL
,COPD	INT NOT NULL
,IncMonth	DATE NOT NULL
,Member_Count	DECIMAL(10,0) NOT NULL
,CoMorbity_Count	DECIMAL(10,0) NOT NULL
,PRIMARY KEY (IDNO) 
);

CREATE TABLE SUM_CLAIMS_CT
(IDNO	INT NOT NULL
,MemberID	INT NOT NULL
,PRODUCT	CHAR(3) NOT NULL
,CLIENT_ID	CHAR(6) NOT NULL
,Gender	CHAR(1) NOT NULL
,AgeRange	VARCHAR(20) NOT NULL
,MemberRegion	VARCHAR(20) NOT NULL
,DIABETES	INT NOT NULL
,CAD	INT NOT NULL
,CHF	INT NOT NULL 
,HYPERTENSION	INT NOT NULL
,COPD	INT NOT NULL
,ProviderID	INT NOT NULL
,ProviderRegion	VARCHAR(20) NOT NULL
,SpecRup_DESC	VARCHAR(100) NOT NULL
,RPT_CD	VARCHAR(10) NOT NULL
,LVL_01	VARCHAR(10) NOT NULL
,LVL_02	VARCHAR(100) NOT NULL
,LVL_03	VARCHAR(100) NOT NULL
,pos_Desc	VARCHAR(100) NOT NULL
,IncMonth	DATE NOT NULL
,CoMorbity_Count	DECIMAL(10,0) NOT NULL
,Cases	DECIMAL(12,0) NOT NULL
,Services	DECIMAL(12,0) NOT NULL
,ClaimCount	DECIMAL(12,0) NOT NULL
,AllowedCharges	DECIMAL(14,2) NOT NULL
,PaidClaims	DECIMAL(14,2) NOT NULL
,MemberPaid	DECIMAL(14,2) NOT NULL
,OPL	DECIMAL(14,2) 
,PRIMARY KEY (IDNO)
);