CREATE TABLE CLAIM_FACT
(IDNO INT NOT NULL
,ClaimID	INT NOT NULL
,ClaimLineNum INT NOT NULL
,ClaimStatusCd CHAR(1) NOT NULL
,ClaimType CHAR(1) NOT NULL
,MemberID	INT NOT NULL
,ProviderID	INT NOT NULL
,posID	INT NOT NULL
,ServiceDate	DATE NOT NULL
,LoadDate	DATE NOT NULL
,Code_Type VARCHAR2(10) NOT NULL
,Code_Value VARCHAR2(10) NOT NULL
,Cases NUMBER(12,0) NOT NULL
,Services NUMBER(12,0) NOT NULL
,AllowedCharges NUMBER(14,2) NOT NULL
,PaidClaims	NUMBER(14,2) NOT NULL
,MemberPaid NUMBER(14,2) NOT NULL
,OPL NUMBER(14,2) NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_PROVIDER
(ProviderID INT NOT NULL
,SpecialtyID INT NOT NULL
,ProviderType INT NOT NULL
,OrgName VARCHAR2(100) NOT NULL
,FirstName	VARCHAR2(100)  NOT NULL
,LastName	VARCHAR2(100) NOT NULL
,address_street	VARCHAR2(255)
,address_city	VARCHAR2(100)
,address_county	VARCHAR2(50)
,address_state	CHAR(2)
,address_zip	CHAR(5)
,PRIMARY KEY (ProviderID)
);

CREATE TABLE DIM_MEMBER
(IDNO	INT NOT NULL
,memberID	INT NOT NULL
,Gender	CHAR(1) NOT NULL
,dateOfBirth	DATE  NOT NULL
,firstname	VARCHAR2(100) NOT NULL
,lastname	VARCHAR2(100) NOT NULL
,address_street	VARCHAR2(255)
,address_city	VARCHAR2(100)
,address_County	VARCHAR2(50)
,address_state	CHAR(2)
,address_zip	CHAR(5) 
,Product	CHAR(3) NOT NULL
,Client_ID CHAR(6) NOT NULL
,StartDate	DATE  NOT NULL
,EndDate	DATE  NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_MEMBER_CONDITION
(IDNO INT NOT NULL
,memberID	INT NOT NULL
,DIABETES INT NOT NULL
,CAD INT NOT NULL
,CHF INT NOT NULL
,HYPERTENSION INT NOT NULL
,COPD INT NOT NULL
,StartDate	DATE  NOT NULL
,EndDate	DATE  NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_DATE
(IncMonth DATE NOT NULL
,IncMonthNum	INT NOT NULL
,StartDate	DATE  NOT NULL
,EndDate	DATE  NOT NULL
,tValue0 INT NOT NULL
,PRIMARY KEY (IncMonth)
);

CREATE TABLE DIM_PLACE_OF_SERVICE
(posID INT NOT NULL
,pos_Desc VARCHAR2(100) NOT NULL
,pos_category VARCHAR2(10) NOT NULL
,PRIMARY KEY (posID)
);

CREATE TABLE DIM_PROVIDER_SPECIALTY
(SpecialtyID INT NOT NULL
,Specialty_Desc	VARCHAR2(100) NOT NULL
,SpecRup_Cd	  VARCHAR2(10) NOT NULL
,SpecRup_DESC	VARCHAR2(100) NOT NULL
,SpecType VARCHAR2(10) NOT NULL
,PRIMARY KEY (SpecialtyID)
);

CREATE TABLE DIM_PROCEDURE
(IDNO INT NOT NULL
,Code_Type VARCHAR2(10) NOT NULL
,Code_Value VARCHAR2(10) NOT NULL
,PROCEDURE_DESC VARCHAR2(255) NOT NULL
,FACILITY_CD VARCHAR2(10) NOT NULL
,PROF_CD VARCHAR2(10) NOT NULL
,PRIMARY KEY (IDNO)
);

CREATE TABLE DIM_REPORTING_CATEGORY
(RPT_CD  VARCHAR2(10) NOT NULL
,LVL_01	VARCHAR2(10) NOT NULL
,LVL_02	VARCHAR2(100) NOT NULL
,LVL_03	VARCHAR2(100) NOT NULL
,PRIMARY KEY (RPT_CD)
);


CREATE TABLE SUM_MEMBER_CT
(IDNO	INT NOT NULL
,MemberID	INT NOT NULL
,PRODUCT	CHAR(3) NOT NULL
,CLIENT_ID	CHAR(6) NOT NULL
,Gender	CHAR(1) NOT NULL
,AgeRange	VARCHAR2(20) NOT NULL
,MemberRegion	VARCHAR2(20) NOT NULL
,DIABETES	INT NOT NULL
,CAD	INT NOT NULL
,CHF	INT NOT NULL
,HYPERTENSION	INT NOT NULL
,COPD	INT NOT NULL
,IncMonth	DATE NOT NULL
,Member_Count	NUMBER(10,0) NOT NULL
,CoMorbity_Count	NUMBER(10,0) NOT NULL
,PRIMARY KEY (IDNO) 
);

CREATE TABLE SUM_CLAIMS_CT
(IDNO	INT NOT NULL
,MemberID	INT NOT NULL
,PRODUCT	CHAR(3) NOT NULL
,CLIENT_ID	CHAR(6) NOT NULL
,Gender	CHAR(1) NOT NULL
,AgeRange	VARCHAR2(20) NOT NULL
,MemberRegion	VARCHAR2(20) NOT NULL
,DIABETES	INT NOT NULL
,CAD	INT NOT NULL
,CHF	INT NOT NULL 
,HYPERTENSION	INT NOT NULL
,COPD	INT NOT NULL
,ProviderID	INT NOT NULL
,ProviderRegion	VARCHAR2(20) NOT NULL
,SpecRup_DESC	VARCHAR2(100) NOT NULL
,RPT_CD	VARCHAR2(10) NOT NULL
,LVL_01	VARCHAR2(10) NOT NULL
,LVL_02	VARCHAR2(100) NOT NULL
,LVL_03	VARCHAR2(100) NOT NULL
,pos_Desc	VARCHAR2(100) NOT NULL
,IncMonth	DATE NOT NULL
,CoMorbity_Count	NUMBER(10,0) NOT NULL
,Cases	NUMBER(12,0) NOT NULL
,Services	NUMBER(12,0) NOT NULL
,ClaimCount	NUMBER(12,0) NOT NULL
,AllowedCharges	NUMBER(14,2) NOT NULL
,PaidClaims	NUMBER(14,2) NOT NULL
,MemberPaid	NUMBER(14,2) NOT NULL
,OPL	NUMBER(14,2) NOT NULL
,PRIMARY KEY (IDNO)
);